<h2>Edit account</h2>
	<div class="container">
		<div class="col-sm-12 col-md-8 mx-auto">
			<form action="<?php
			 echo APP_URL.'accounts/update'; ?>" method="POST">
				<input type="hidden" value="<?php echo $this->account['id']; ?>" name="id">
				<div class="form-group">
					<label for="name">Name</label>
					<input type="text" class="form-control" name="name" value="<?php echo $this->account['name']; ?>">
				</div>	
				<button class="btn btn-sm btn-primary pull-right"  type="submit">Save</button>
			</form>
		</div>
	</div>