<h2>Add task</h2>
	<div class="container">
		<div class="col-md-6 mx-auto">
			<form action="<?php
			echo APP_URL.'transactions/add'; ?>" method="POST">
			<div class="form-group">
				<label for="id_account">Account</label>
				<select name="id_account" class="form-control" >
				<?php foreach ($this->accounts as $account): ?>
					<?php echo "<option value='".$account['id']."'>".$account['name']."</option>"; ?>
				<?php endforeach ?>
			</select>
			</div>
				<div class="form-group">
					<label for="id_category">Category</label>
					<select name="id_category" class="form-control">
						<?php foreach ($this->categories as $category): ?>
							<?php echo "<option value='".$category['id']."''>".$category['name']."</option>"; ?>
						<?php endforeach ?>
					</select>
				</div>
				<div class="form-group">
					<label for="date">Fecha</label>
					<input type="date" name="date" class="form-control" value="<?php echo date('Y-m-d'); ?>">
				</div>
				<div class="form-group">
					<label for="description">Description</label>
					<input type="text_area" class="form-control" name="description">
				</div>
				<div class="form-group">
					<label for="amount">Amount</label>
					<input type="text" class="form-control" name="amount">
				</div>
				<button class="button btn btn-primary pull-right" type="submit">Save</button>
			</form>
		</div>
	</div>