<h2>Transaction list</h2>
	<div class="container">
		<div class="col-md-12">
			<?php
			$cantIngresos=0;
			$cantEgresos=0;
	 		if (!empty($this->transactions)): ?>
			<table class="table table-sm table-dark">
				<thead class="table table-dark table-bordered">
					<tr>
						<th>Account</th>
						<th>Category</th>
						<th>Description</th>
						<th>Date</th>
						<th>Amount</th>
						<th>Options</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->transactions as $transaction): ?>
					<tr>
						<td>
						<?php
							echo $transaction['nameaccount']; ?>
						</td>
						<td>
							<?php echo $transaction['namecategory']; ?>
						</td>
						<td>
							<?php echo $transaction['description']; ?>
						</td>
						<td>
							<?php 
							$date = date_create($transaction['date']);
							echo date_format($date,'d/m/Y');
							 ?>
						</td>
						<td>
							<?php 
								if ($transaction['amount'] > 0) 
								{
									$cantIngresos=$cantIngresos+$transaction['amount'];
									$money =number_format((float)$transaction['amount'] , 2, '.', '');
									echo "<label style='color:blue'>"."$".$money."</label>";
								}
								if ($transaction['amount'] <0) 
								{	
									$cantEgresos=$cantEgresos+$transaction['amount'];
									$money =number_format((float)$transaction['amount'] , 2, '.', '');
									echo "<label style='color:orange;'>"."$".$money."</label>";
								}
							?>	
						</td>
						<td>	
							<a href="<?php echo APP_URL.'transactions/update/'.$transaction['id']; ?>">
								<button class="btn btn-sm btn-success">
									<i class="glyphicon glyphicon-pencil"></i>
								</button>
							</a>
							<a href="<?php echo APP_URL.'transactions/delete/'.$transaction['id']; ?>">
								<button class="btn btn-sm btn-warning confirmation">
									<i class="glyphicon glyphicon-trash"></i>
								</button>
							</a>
						</td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
		<a href="<?php
			echo APP_URL.'transactions/add'; ?>">
				<button class="btn btn-sm btn-dark">
				<i class="glyphicon glyphicon-plus"></i>
			Add transaction
		</button>
			</a>
		<div class="responsive">
			<div class="col-md-4 pull-right">
			<div class="form-group">
				<div class="col-xs-6 ">
				<label for="id_account">Income:</label>
				</div>
				<div class="col-xs-4 ">
				<?php  echo "<label>".$cantIngresos."</label>";?> 
				</div>
			</div>
			<div class="form-group">
				<div class="col-xs-6 ">
				<label for="id_account">Expenses:</label>
				</div>
				<div class="col-xs-4">
				<?php  echo "<label style='color:red'>".$cantEgresos."</label>";?> 
				</div>
			</div>
			<div class="form-group">
				<div class="col-xs-6">
				<label for="id_account">Balance:</label>
				</div>
				<div class="col-xs-4">
				<?php
				$balance=0;
				$balance=$cantIngresos+$cantEgresos;
				if($balance>0){ echo "<label style='color:green;'>"."$".$balance."</label>";}
				else{ echo "<label style='color:red;'>"."$".$balance."</label>";}	
				 ?>
				</div>
			</div>
			</div>
		</div>
		<?php else: ?>
			<div>
				Registers not found.
			</div>
		<?php endif ?>
	</div>
</div>